apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector:
    app: grafana-deployment-xfusion # change this to match your deployment's label
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000 # Grafana default port
      targetPort: 3000
      nodePort: 32000
  