apiVersion: v1
kind: Service
metadata:
  name: tomcat-service-datacenter
  namespace: tomcat-namespace-datacenter
spec:
  selector:
    app: tomcat-datacenter # change this to match your deployment's label
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080 # Tomcat default port
      targetPort: 8080 # Port on the container
      nodePort: 32227
  